ALTER TYPE "public"."wa_event_type" ADD VALUE 'termination_pending';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'termination_approved';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'termination_cancelled';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'domain_expired';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'domain_renewed';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'order_approved';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_activated';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'backup_success';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'backup_failed';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'invoice_overdue';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'invoice_generated';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'low_balance';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'cron_failed';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'migration_failed';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'migration_completed';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'abuse_report';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'security_alert';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'login_failed';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'payment_failed';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_expired';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_renewed';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_terminated';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_pending';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_active';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_admin';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_client';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_abuse';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_fraud';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_nonpayment';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_auto';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_terminated';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_pending';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_active';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_inactive';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_maintenance';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_unknown';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_other';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_custom';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_system';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_admin';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_client';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_abuse';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_fraud';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_nonpayment';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_manual';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_auto';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_terminated';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_pending';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_active';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_inactive';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_maintenance';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_unknown';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_other';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_custom';--> statement-breakpoint
ALTER TYPE "public"."wa_event_type" ADD VALUE 'service_suspended_manual_system';