/**
 * Noehost Professional Invoice PDF Generator
 * Guaranteed single-page A4 layout — compact, clean, premium brand.
 */
import PDFDocument from "pdfkit";

export interface InvoiceItem {
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

export interface InvoiceData {
  invoiceNumber: string;
  status: string;
  createdAt: string;
  dueDate: string;
  paidDate?: string | null;
  clientName: string;
  clientEmail?: string;
  amount: number;
  tax: number;
  total: number;
  creditApplied?: number;
  items: InvoiceItem[];
  paymentRef?: string | null;
  paymentNotes?: string | null;
}

// ── Palette ───────────────────────────────────────────────────────────────────
const BRAND    = "#701AFE";
const PAID_C   = "#16a34a";
const UNPAID_C = "#dc2626";
const GREY     = "#6B7280";
const DARK     = "#1e293b";
const SLATE50  = "#F8FAFC";
const SLATE100 = "#F1F5F9";
const SLATE200 = "#E2E8F0";
const WHITE    = "#FFFFFF";

// ── Helpers ───────────────────────────────────────────────────────────────────
function formatPKR(amount: number): string {
  return `Rs. ${Number(amount).toLocaleString("en-PK", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function fmtDate(iso: string | null | undefined): string {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleDateString("en-GB", {
      day: "numeric", month: "short", year: "numeric",
    });
  } catch { return "—"; }
}

export function generateInvoicePdf(data: InvoiceData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const MARGIN = 40;
    const doc = new PDFDocument({
      size: "A4",
      margin: MARGIN,
      bufferPages: true,
      autoFirstPage: true,
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const PW = doc.page.width;   // 595.28
    const PH = doc.page.height;  // 841.89
    const L  = MARGIN;
    const R  = PW - MARGIN;
    const W  = R - L;            // 515.28

    const isPaid      = data.status === "paid";
    const isUnpaid    = ["unpaid", "overdue"].includes(data.status);
    const isCancelled = data.status === "cancelled";
    const statusLabel = data.status === "payment_pending"
      ? "PENDING"
      : data.status.replace("_", " ").toUpperCase();
    const statusColor = isPaid ? PAID_C : isCancelled ? GREY : UNPAID_C;

    const creditApplied     = data.creditApplied ?? 0;
    const amountAfterCredit = Number(data.total) - creditApplied;

    // ──────────────────────────────────────────────────────────────────────────
    // FOOTER BAND — drawn first at absolute bottom, so content never pushes it
    // ──────────────────────────────────────────────────────────────────────────
    const FOOTER_H = 52;
    const FOOTER_Y = PH - FOOTER_H;
    // Bottom boundary for content — stay well above footer
    const CONTENT_BOTTOM = FOOTER_Y - 8;

    doc.rect(0, FOOTER_Y, PW, FOOTER_H).fill(BRAND);
    doc.font("Helvetica-Bold").fontSize(9).fillColor(WHITE);
    doc.text("Thank you for choosing Noehost!", 0, FOOTER_Y + 9, { width: PW, align: "center" });
    doc.font("Helvetica").fontSize(7).fillColor("rgba(255,255,255,0.60)");
    doc.text("support@noehost.com  ·  noehost.com  ·  billing@noehost.com",
      0, FOOTER_Y + 23, { width: PW, align: "center" });
    doc.font("Helvetica").fontSize(6.5).fillColor("rgba(255,255,255,0.38)");
    doc.text(`Invoice #${data.invoiceNumber} — Generated by Noehost Billing System`,
      0, FOOTER_Y + 36, { width: PW, align: "center" });

    // ──────────────────────────────────────────────────────────────────────────
    // HEADER BAND
    // ──────────────────────────────────────────────────────────────────────────
    const HEADER_H = 90;
    doc.rect(0, 0, PW, HEADER_H).fill(BRAND);

    // Noehost logo text
    doc.font("Helvetica-Bold").fontSize(19).fillColor(WHITE);
    doc.text("N", L, 22, { continued: true, lineBreak: false });
    doc.font("Helvetica").text("oehost");
    doc.font("Helvetica").fontSize(7.5).fillColor("rgba(255,255,255,0.60)");
    doc.text("Professional Hosting Solutions", L, 46, { lineBreak: false });
    doc.text("billing@noehost.com", L, 57, { lineBreak: false });

    // Invoice number (right)
    doc.font("Helvetica").fontSize(7.5).fillColor("rgba(255,255,255,0.55)");
    doc.text("INVOICE", 0, 22, { width: PW - MARGIN, align: "right", lineBreak: false });
    doc.font("Helvetica-Bold").fontSize(22).fillColor(WHITE);
    doc.text(`#${data.invoiceNumber}`, 0, 33, { width: PW - MARGIN, align: "right", lineBreak: false });

    // Status badge (red pill for unpaid, green for paid, etc.)
    const badgeW = 82;
    const badgeH = 16;
    doc.roundedRect(R - badgeW, 65, badgeW, badgeH, 4).fill(statusColor);
    doc.font("Helvetica-Bold").fontSize(7).fillColor(WHITE);
    doc.text(statusLabel, R - badgeW, 70, { width: badgeW, align: "center", lineBreak: false });

    // ──────────────────────────────────────────────────────────────────────────
    // CONTENT — compact, absolute-y drawing to prevent auto page-break
    // ──────────────────────────────────────────────────────────────────────────
    let y = HEADER_H + 10;

    // DATE ROW
    const DR_H = 30;
    doc.rect(L, y, W, DR_H).fill(SLATE100);
    const dateCols = [
      { label: "Invoice Date", value: fmtDate(data.createdAt) },
      { label: "Due Date",     value: fmtDate(data.dueDate)   },
      { label: "Paid Date",    value: isPaid ? fmtDate(data.paidDate) : "—" },
    ];
    const colW = W / 3;
    dateCols.forEach((col, i) => {
      const cx = L + i * colW;
      doc.font("Helvetica").fontSize(6).fillColor(GREY);
      doc.text(col.label.toUpperCase(), cx + 4, y + 5, { width: colW - 8, align: "center", lineBreak: false });
      doc.font("Helvetica-Bold").fontSize(8.5).fillColor(DARK);
      doc.text(col.value, cx + 4, y + 14, { width: colW - 8, align: "center", lineBreak: false });
      if (i < 2) doc.rect(cx + colW - 0.5, y + 4, 0.5, 22).fill(SLATE200);
    });
    y += DR_H + 10;

    // BILL FROM / BILL TO
    const halfW = (W - 12) / 2;
    const billToX = L + halfW + 12;
    const billStartY = y;

    doc.font("Helvetica-Bold").fontSize(6).fillColor(BRAND);
    doc.text("PAY TO", L, y, { lineBreak: false });
    y += 9;
    doc.font("Helvetica-Bold").fontSize(10).fillColor(DARK);
    doc.text("Noehost", L, y, { lineBreak: false });
    y += 12;
    doc.font("Helvetica").fontSize(7.5).fillColor(GREY);
    doc.text("billing@noehost.com", L, y, { lineBreak: false });
    y += 9;
    doc.text("support@noehost.com", L, y, { lineBreak: false });
    y += 9;

    // Bill To column (absolute, same start y)
    let bty = billStartY;
    doc.font("Helvetica-Bold").fontSize(6).fillColor(BRAND);
    doc.text("BILL TO", billToX, bty, { lineBreak: false });
    bty += 9;
    doc.font("Helvetica-Bold").fontSize(10).fillColor(DARK);
    doc.text(data.clientName || "Client", billToX, bty, { lineBreak: false });
    bty += 12;
    if (data.clientEmail) {
      doc.font("Helvetica").fontSize(7.5).fillColor(GREY);
      doc.text(data.clientEmail, billToX, bty, { lineBreak: false });
    }

    // Divider between columns
    doc.rect(L + halfW + 5, billStartY, 0.5, 42).fill(SLATE200);

    y = billStartY + 42 + 8;

    // Thin divider
    doc.rect(L, y, W, 0.5).fill(SLATE200);
    y += 9;

    // ITEMS TABLE — header row
    const ROW_H = 18;
    doc.roundedRect(L, y, W, 20, 2).fill(BRAND);
    doc.font("Helvetica-Bold").fontSize(7).fillColor(WHITE);
    doc.text("DESCRIPTION", L + 6,  y + 6, { width: W * 0.52, lineBreak: false });
    doc.text("QTY",          L + W * 0.54, y + 6, { width: W * 0.08, align: "center", lineBreak: false });
    doc.text("UNIT PRICE",   L + W * 0.63, y + 6, { width: W * 0.18, align: "right",  lineBreak: false });
    doc.text("AMOUNT",       L + W * 0.83, y + 6, { width: W * 0.15, align: "right",  lineBreak: false });
    y += 20;

    const items = data.items && data.items.length > 0
      ? data.items
      : [{ description: "Service", quantity: 1, unitPrice: data.amount, total: data.amount }];

    // Cap at 10 items to guarantee single page
    const visibleItems = items.slice(0, 10);
    visibleItems.forEach((item, idx) => {
      doc.rect(L, y, W, ROW_H).fill(idx % 2 === 0 ? WHITE : SLATE50);
      doc.font("Helvetica").fontSize(7.5).fillColor(DARK);
      doc.text(item.description, L + 6, y + 4, { width: W * 0.51, lineBreak: false, ellipsis: true });
      doc.fillColor(GREY);
      doc.text(String(item.quantity), L + W * 0.54, y + 4, { width: W * 0.08, align: "center", lineBreak: false });
      doc.fillColor(DARK);
      doc.text(formatPKR(Number(item.unitPrice)), L + W * 0.63, y + 4, { width: W * 0.18, align: "right", lineBreak: false });
      doc.font("Helvetica-Bold");
      doc.text(formatPKR(Number(item.total)), L + W * 0.83, y + 4, { width: W * 0.15, align: "right", lineBreak: false });
      y += ROW_H;
    });

    doc.rect(L, y, W, 0.5).fill(SLATE200);
    y += 9;

    // TOTALS
    const totalsX = L + W * 0.54;
    const totalsW = W * 0.46;

    const totalsRows: { label: string; value: string; color?: string; bold?: boolean }[] = [
      { label: "Subtotal",       value: formatPKR(data.amount) },
      { label: "Tax / VAT (0%)", value: formatPKR(data.tax || 0) },
    ];
    if (creditApplied > 0) {
      totalsRows.push({
        label: "Account Credit Applied",
        value: `- ${formatPKR(creditApplied)}`,
        color: PAID_C, bold: true,
      });
    }

    totalsRows.forEach(row => {
      doc.font(row.bold ? "Helvetica-Bold" : "Helvetica").fontSize(8).fillColor(row.color ?? GREY);
      doc.text(row.label, totalsX, y, { width: totalsW * 0.55, lineBreak: false });
      doc.fillColor(row.color ?? DARK);
      doc.text(row.value, totalsX + totalsW * 0.55, y, { width: totalsW * 0.45, align: "right", lineBreak: false });
      y += 12;
    });

    // Total Due band
    doc.roundedRect(totalsX - 4, y - 1, totalsW + 8, 24, 3).fill(BRAND);
    doc.font("Helvetica-Bold").fontSize(9).fillColor(WHITE);
    doc.text("TOTAL DUE", totalsX, y + 6, { width: totalsW * 0.55, lineBreak: false });
    doc.text(
      formatPKR(creditApplied > 0 ? amountAfterCredit : data.total),
      totalsX + totalsW * 0.55, y + 6,
      { width: totalsW * 0.45, align: "right", lineBreak: false }
    );
    y += 30;

    // Payment reference (optional, compact)
    if (data.paymentRef) {
      doc.font("Helvetica").fontSize(7).fillColor(GREY);
      doc.text(`Payment Ref: ${data.paymentRef}${data.paymentNotes ? "  |  Notes: " + data.paymentNotes : ""}`,
        L, y, { width: W, lineBreak: false, ellipsis: true });
      y += 10;
    }

    y += 4;

    // CEO SIGNATURE — compact grey box
    doc.rect(L, y, W, 0.5).fill(SLATE200);
    y += 8;

    const SIG_H = 46;
    doc.roundedRect(L, y, W * 0.62, SIG_H, 3).fill(SLATE100);

    doc.font("Helvetica-Bold").fontSize(6).fillColor(GREY);
    doc.text("AUTHORIZED & ISSUED BY", L + 8, y + 6, { width: W * 0.58, lineBreak: false });

    doc.font("Helvetica-Bold").fontSize(12).fillColor(BRAND);
    doc.text("Muhammad Arslan", L + 8, y + 16, { lineBreak: false });

    doc.font("Helvetica").fontSize(7.5).fillColor(DARK);
    doc.text("Founder & CEO, Noehost", L + 8, y + 31, { lineBreak: false });

    doc.font("Helvetica-Oblique").fontSize(6.5).fillColor(GREY);
    doc.text(
      '"Empowering your digital journey with premium hosting solutions."',
      L + 8, y + 41,
      { width: W * 0.58, lineBreak: false, ellipsis: true }
    );

    y += SIG_H + 8;

    // TERMS & CONDITIONS — single compact line
    doc.rect(L, y, W, 0.5).fill(SLATE200);
    y += 7;
    doc.font("Helvetica-Bold").fontSize(6).fillColor(GREY);
    doc.text("TERMS & CONDITIONS", L, y, { lineBreak: false });
    y += 8;
    doc.font("Helvetica").fontSize(6.5).fillColor(GREY);
    doc.text(
      "All services are governed by Noehost TOS (noehost.com/tos). Invoices must be paid by the due date to avoid service interruption. Thank you for choosing Noehost!",
      L, y, { width: W, lineBreak: true }
    );

    // Finalize — only one page should exist
    doc.end();
  });
}
