import { Router, type IRouter } from "express";
import { routeLogger } from "../lib/auth.js";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import clientsRouter from "./clients.js";
import hostingRouter from "./hosting.js";
import domainsRouter from "./domains.js";
import domainRenewalsAdminRouter from "./domain-renewals-admin.js";
import packagesRouter from "./packages.js";
import ordersRouter from "./orders.js";
import invoicesRouter from "./invoices.js";
import ticketsRouter from "./tickets.js";
import migrationsRouter from "./migrations.js";
import dashboardRouter from "./dashboard.js";
import promoCodesRouter from "./promo-codes.js";
import paymentMethodsRouter from "./payment-methods.js";
import checkoutRouter from "./checkout.js";
import domainExtensionsRouter from "./domain-extensions.js";
import currenciesRouter from "./currencies.js";
import serversRouter from "./servers.js";
import productGroupsRouter from "./product-groups.js";
import emailTemplatesRouter from "./email-templates.js";
import fraudRouter from "./fraud.js";
import cronLogsRouter from "./cron-logs.js";
import serverLogsRouter from "./server-logs.js";
import settingsRouter from "./settings.js";
import affiliatesRouter from "./affiliates.js";
import domainTransfersRouter from "./domain-transfers.js";
import creditsRouter from "./credits.js";
import notificationsRouter from "./notifications.js";
import activityLogsRouter from "./activity-logs.js";
import dnsRouter from "./dns.js";
import vpsRouter from "./vps.js";
import whmcsImportRouter from "./whmcsImport.js";
import adminUsersRouter from "./admin-users.js";
import kbRouter from "./kb.js";
import securityRouter from "./security.js";
import modulesRouter from "./modules.js";
import domainRegistrarsRouter from "./domain-registrars.js";
import domainActivationRouter from "./domain-activation.js";
import whatsappRouter from "./whatsapp.js";
import serverStatusRouter from "./server-status.js";
import announcementsRouter from "./announcements.js";
import safepayRouter from "./safepay.js";
import contactRouter from "./contact.js";
import configRouter from "./config.js";
import syncRouter from "./sync.js";
import globalRouter from "./global.js";
import domainSearchRouter from "./domain-search.js";
import setupProgressRouter from "./setup-progress.js";
import backupsRouter from "./backups.js";
import emailMarketingRouter from "./email-marketing.js";
import cartRouter from "./cart.js";
import twentyIAdminRouter from "./twenty-i-admin.js";
import systemRouter from "./system.js";

const router: IRouter = Router();

// ─── Global Route Logger ──────────────────────────────────────────────────────
router.use(routeLogger);

// ─── Route Modules ────────────────────────────────────────────────────────────
// To add a new section: create a router file, import it here, add router.use().
router.use(healthRouter);
router.use(authRouter);
router.use(clientsRouter);
router.use(hostingRouter);
router.use(domainRenewalsAdminRouter);
router.use(domainsRouter);
router.use(packagesRouter);
router.use(ordersRouter);
router.use(invoicesRouter);
router.use(ticketsRouter);
router.use(migrationsRouter);
router.use(dashboardRouter);
router.use(promoCodesRouter);
router.use(paymentMethodsRouter);
router.use(checkoutRouter);
router.use(domainExtensionsRouter);
router.use(currenciesRouter);
router.use(serversRouter);
router.use(productGroupsRouter);
router.use(emailTemplatesRouter);
router.use(fraudRouter);
router.use(cronLogsRouter);
router.use(serverLogsRouter);
router.use(settingsRouter);
router.use(affiliatesRouter);
router.use(domainTransfersRouter);
router.use(creditsRouter);
router.use(notificationsRouter);
router.use(activityLogsRouter);
router.use(dnsRouter);
router.use(vpsRouter);
router.use(whmcsImportRouter);
router.use(adminUsersRouter);
router.use(kbRouter);
router.use(securityRouter);
router.use(modulesRouter);
router.use(domainRegistrarsRouter);
router.use(domainActivationRouter);
router.use(whatsappRouter);
router.use(serverStatusRouter);
router.use(announcementsRouter);
router.use(safepayRouter);
router.use(contactRouter);
router.use(configRouter);
router.use(syncRouter);
router.use(globalRouter);
router.use(domainSearchRouter);
router.use(setupProgressRouter);
router.use(backupsRouter);
router.use(emailMarketingRouter);
router.use(cartRouter);
router.use(twentyIAdminRouter);
router.use(systemRouter);

export default router;
