import { pgTable, text, timestamp, numeric, integer, boolean, pgEnum } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const billingCycleEnum = pgEnum("billing_cycle", ["monthly", "yearly"]);
export const hostingStatusEnum = pgEnum("hosting_status", ["active", "suspended", "terminated", "pending", "pending_termination"]);

export const hostingPlansTable = pgTable("hosting_plans", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  name: text("name").notNull(),
  description: text("description"),
  price: numeric("price", { precision: 10, scale: 2 }).notNull(),
  yearlyPrice: numeric("yearly_price", { precision: 10, scale: 2 }),
  quarterlyPrice: numeric("quarterly_price", { precision: 10, scale: 2 }),
  semiannualPrice: numeric("semiannual_price", { precision: 10, scale: 2 }),
  billingCycle: billingCycleEnum("billing_cycle").notNull().default("monthly"),
  groupId: text("group_id"),
  module: text("module").default("none"),
  moduleServerId: text("module_server_id"),
  moduleServerGroupId: text("module_server_group_id"),
  modulePlanId: text("module_plan_id"),
  modulePlanName: text("module_plan_name"),
  diskSpace: text("disk_space").notNull(),
  bandwidth: text("bandwidth").notNull(),
  emailAccounts: integer("email_accounts").default(10),
  databases: integer("databases").default(5),
  subdomains: integer("subdomains").default(10),
  ftpAccounts: integer("ftp_accounts").default(5),
  isActive: boolean("is_active").default(true),
  features: text("features").array().default([]),
  renewalEnabled: boolean("renewal_enabled").default(true),
  renewalPrice: numeric("renewal_price", { precision: 10, scale: 2 }),
  freeDomainEnabled: boolean("free_domain_enabled").default(false),
  freeDomainTlds: text("free_domain_tlds").array().default([]),
  saveAmount: numeric("save_amount", { precision: 10, scale: 2 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const hostingServicesTable = pgTable("hosting_services", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  clientId: text("client_id").notNull(),
  orderId: text("order_id"),
  planId: text("plan_id").notNull(),
  planName: text("plan_name").notNull(),
  domain: text("domain"),
  username: text("username"),
  password: text("password"),
  serverId: text("server_id"),
  serverIp: text("server_ip").default("192.168.1.1"),
  status: hostingStatusEnum("status").notNull().default("pending"),
  billingCycle: text("billing_cycle").default("monthly"),
  nextDueDate: timestamp("next_due_date"),
  sslStatus: text("ssl_status").default("not_installed"),
  startDate: timestamp("start_date").defaultNow(),
  expiryDate: timestamp("expiry_date"),
  diskUsed: text("disk_used").default("0 MB"),
  bandwidthUsed: text("bandwidth_used").default("0 GB"),
  cpanelUrl: text("cpanel_url"),
  webmailUrl: text("webmail_url"),
  cancelRequested: boolean("cancel_requested").default(false),
  cancelReason: text("cancel_reason"),
  cancelRequestedAt: timestamp("cancel_requested_at"),
  autoRenew: boolean("auto_renew").default(true),
  freeDomainAvailable: boolean("free_domain_available").default(false),
  freeDomainId: text("free_domain_id"),
  wpInstalled: boolean("wp_installed").default(false),
  wpUrl: text("wp_url"),
  wpUsername: text("wp_username"),
  wpPassword: text("wp_password"),
  wpEmail: text("wp_email"),
  wpSiteTitle: text("wp_site_title"),
  wpDbName: text("wp_db_name"),
  wpContainerId: text("wp_container_id"),
  wpPort: integer("wp_port"),
  wpProvisionStatus: text("wp_provision_status").default("not_started"),
  wpProvisionStep: text("wp_provision_step"),
  wpProvisionError: text("wp_provision_error"),
  wpProvisionedAt: timestamp("wp_provisioned_at"),
  wpInstallPath: text("wp_install_path").default("/"),
  wpPasswordRevealed: boolean("wp_password_revealed").default(false),
  serviceType: text("service_type").default("shared"),
  vpsPlanId: text("vps_plan_id"),
  vpsOsTemplate: text("vps_os_template"),
  vpsLocation: text("vps_location"),
  vpsHostname: text("vps_hostname"),
  vpsRootUser: text("vps_root_user"),
  vpsRootPassword: text("vps_root_password"),
  vpsImageId: text("vps_image_id"),
  vpsAutoRenew: boolean("vps_auto_renew").default(true),
  vpsWeeklyBackups: boolean("vps_weekly_backups").default(false),
  vpsProvisionStatus: text("vps_provision_status").default("not_started"),
  vpsProvisionedAt: timestamp("vps_provisioned_at"),
  vpsProvisionNotes: text("vps_provision_notes"),
  whmcsId: text("whmcs_id"),
  twentyIPackageId: text("twenty_i_package_id"),
  amount: numeric("amount", { precision: 10, scale: 2 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const insertHostingPlanSchema = createInsertSchema(hostingPlansTable).omit({ id: true, createdAt: true });
export type InsertHostingPlan = z.infer<typeof insertHostingPlanSchema>;
export type HostingPlan = typeof hostingPlansTable.$inferSelect;

export const insertHostingServiceSchema = createInsertSchema(hostingServicesTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertHostingService = z.infer<typeof insertHostingServiceSchema>;
export type HostingService = typeof hostingServicesTable.$inferSelect;
