import { pgTable, text, timestamp, pgEnum } from "drizzle-orm/pg-core";

export const waEventEnum = pgEnum("wa_event_type", [
  "new_order",
  "new_ticket",
  "payment_proof",
  "test",
  "other",
  "refund_request",
  "invoice_paid",
  "client_notification",
  "admin_command",
  "suspension_warning",
  "termination_pending",
  "termination_approved",
  "termination_cancelled",
  "domain_expired",
  "domain_renewed",
  "order_approved",
  "service_suspended",
  "service_activated",
  "backup_success",
  "backup_failed",
  "invoice_overdue",
  "invoice_generated",
  "low_balance",
  "cron_failed",
  "migration_failed",
  "migration_completed",
  "abuse_report",
  "security_alert",
  "login_failed",
  "payment_failed",
  "service_expired",
  "service_renewed",
  "service_terminated",
  "service_pending",
  "service_active",
  "service_suspended_admin",
  "service_suspended_client",
  "service_suspended_abuse",
  "service_suspended_fraud",
  "service_suspended_nonpayment",
  "service_suspended_manual",
  "service_suspended_auto",
  "service_suspended_terminated",
  "service_suspended_pending",
  "service_suspended_active",
  "service_suspended_inactive",
  "service_suspended_maintenance",
  "service_suspended_unknown",
  "service_suspended_other",
  "service_suspended_custom",
  "service_suspended_system",
  "service_suspended_manual_admin",
  "service_suspended_manual_client",
  "service_suspended_manual_abuse",
  "service_suspended_manual_fraud",
  "service_suspended_manual_nonpayment",
  "service_suspended_manual_manual",
  "service_suspended_manual_auto",
  "service_suspended_manual_terminated",
  "service_suspended_manual_pending",
  "service_suspended_manual_active",
  "service_suspended_manual_inactive",
  "service_suspended_manual_maintenance",
  "service_suspended_manual_unknown",
  "service_suspended_manual_other",
  "service_suspended_manual_custom",
  "service_suspended_manual_system",
]);

export const whatsappLogsTable = pgTable("whatsapp_logs", {
  id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
  eventType: waEventEnum("event_type").notNull().default("other"),
  message: text("message").notNull(),
  status: text("status").notNull().default("sent"),
  errorMessage: text("error_message"),
  sentAt: timestamp("sent_at").defaultNow().notNull(),
});

export type WhatsappLog = typeof whatsappLogsTable.$inferSelect;
